name = "MPFI"
uuid = "e50a78b8-6e2f-482e-b7c3-776aa2235d1a"
authors = ["Christina Katsamaki"]
version = "0.0.3"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
MPFI_jll = "e8b5fb6c-218f-5c08-bc3d-6b0e551bbffd"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
